pipeline {
   agent any

   stages {
      stage('Build & Test') {
         steps {
            // Get some code from a GitHub repository
            git 'git@github.com:eduardobreno/caelum-formacao-devops.git'

            // Run Maven on a Unix agent.
            sh "mvn -Dmaven.test.failure.ignore=true clean package"
            //sh "mvn clean test"
            // To run Maven on a Windows agent, use
            // bat "mvn -Dmaven.test.failure.ignore=true clean package"
         }

         post {
            // If Maven was able to run the tests, even if some of the test
            // failed, record the test results and archive the jar file.
            // always {
            //   junit '**/target/surefire-reports/TEST-*.xml'
            // }
            success {
               archiveArtifacts 'target/*.war'
            }
         }
      }
   }
}
